// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParkDirectoryApi.Models;

namespace NationalParkDirectoryApi.Migrations
{
    [DbContext(typeof(NationalParkDirectoryApiContext))]
    partial class NationalParkDirectoryApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParkDirectoryApi.Models.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlphaCode");

                    b.Property<string>("Name");

                    b.Property<string>("Region");

                    b.Property<string>("StateCode");

                    b.Property<string>("Url");

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");
                });
#pragma warning restore 612, 618
        }
    }
}
